### ISSUE TITLE
UndeliverableException crashes Android app

### ISSUE THREAD

**Issue by xvrh** [PhilipsHue/flutter_reactive_ble#154]
**Describe the bug**
A user reports that my app crashes when connecting to an IoT peripheral.
I see this in crashlytics:

```
Fatal Exception: f.d.z.f: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | d.f.a.m0.f: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 8 (GATT_INSUF_AUTHORIZATION or GATT_CONN_TIMEOUT)
       at io.reactivex.plugins.RxJavaPlugins.b(RxJavaPlugins.java:20)
       at io.reactivex.internal.operators.observable.ObservableUnsubscribeOn$UnsubscribeObserver.a(ObservableUnsubscribeOn.java:6)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.a(ObservableCreate.java:17)
       at com.polidea.rxandroidble2.internal.util.QueueReleasingEmitterWrapper.a(QueueReleasingEmitterWrapper.java:7)
       at io.reactivex.internal.observers.DeferredScalarDisposable.b(DeferredScalarDisposable.java:18)
       at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.dispose(SingleToObservable.java)
       at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.a(SingleTimeout.java:23)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.a(SingleMap.java:2)
       at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.a(ObservableElementAtSingle.java:13)
       at io.reactivex.internal.observers.BasicFuseableObserver.a(BasicFuseableObserver.java:13)
       at io.reactivex.observers.SerializedObserver.a(SerializedObserver.java:64)
       at io.reactivex.internal.operators.observable.ObservableDelay$DelayObserver$OnError.run(ObservableDelay.java:6)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:13)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by d.f.a.m0.f: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 8 (GATT_INSUF_AUTHORIZATION or GATT_CONN_TIMEOUT)
       at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:42)
       at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:272)
       at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
       at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
       at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:267)
       at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:192)
       at android.os.Binder.execTransactInternal(Binder.java:1159)
       at android.os.Binder.execTransact(Binder.java:1123)
```

**To Reproduce**
I don't have reproduction step unfortunately.

**Expected behavior**
I think the Bluetooth library should try to never crash the app (even when not used correctly).

**Smartphone / tablet**
 - Device: Android Pixel 3a
 - OS: Android 11
 - Package version: 2.7.1

**Peripheral device**
- Vendor, model: Cypress Psoc4 
- Does it run a custom firmware / software: yes

**Additional context**
I found this document that seems related: https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-UndeliverableException

Thanks a lot.

**Comment by xvrh** [comment]
Ok, I see the fix is right in the README. Sorry about that.
