### ISSUE TITLE
Is null safety already implemented in this library?

### ISSUE THREAD

**Issue by realrk69** [PhilipsHue/flutter_reactive_ble#158]
I've created a bluetooth connection screen and in debug mode:

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The getter 'key' was called on null.
Receiver: null
Tried calling: key

The relevant error-causing widget was: 
  StaggeredGridView file:///C:/Users/realr/Desktop/RAAV/app/lib/screens/BleConnectionScreen.dart:136:34
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SliverChildListDelegate.build (package:flutter/src/widgets/sliver.dart:679:27)
#2      SliverVariableSizeBoxAdaptorElement._build.<anonymous closure> (package:flutter_staggered_grid_view/src/widgets/sliver.dart:144:38)
#3      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
#4      SliverVariableSizeBoxAdaptorElement._build (package:flutter_staggered_grid_view/src/widgets/sliver.dart:143:26)
```
Never seen such an error before in Flutter, and I've been using it for almost 8 months now.

**Comment by realrk69** [comment]
Got it, I initialized the instances of ble at buildcontext instead of before runapp
