### ISSUE TITLE
Android: crash with 2.7.3

### ISSUE THREAD

**Issue by il-picchio** [PhilipsHue/flutter_reactive_ble#214]
**Describe the bug**
Only with Android.
The app crashes using the plugin version 2.7.3, with 2.7.2 it works flawlessly (great job, the best right now).
The crash occurs only when the app is built in release mode (--release).

**To Reproduce**
1. Init reactive client
2. Start to scan

**Expected behavior**
The app doesn't crash as previous plugin version :D

**Smartphone / tablet**
 - Device: Nokia 4.2 / Samsung J5 / Oneplus 7 Pro
 - OS: Android 10 / Android 9 / Android 10
 - Package version: 2.7.3

**Peripheral device**
- Vendor, model: CUSTOM
- Does it run a custom firmware / software: yes

**Additional context**
StackTrace:

Fatal Exception: d.b.z.a: 2 exceptions occurred. 
       at io.reactivex.internal.observers.LambdaObserver.a(LambdaObserver.java:32)
       at io.reactivex.internal.observers.LambdaObserver.a(LambdaObserver.java:25)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:47)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:8)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

----------------------

Caused by d.b.z.a$a: Chain of Causes for CompositeException In Order Received =>
       at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:29)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.a(CrashlyticsReportDataCapture.java:18)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.a(SessionReportingCoordinator.java:19)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.a(SessionReportingCoordinator.java:32)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.call(CrashlyticsController.java:53)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.call(CrashlyticsController.java)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:2)
       at com.google.android.gms.tasks.zzf.run(zzf.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:919)

----------------------

Caused by java.lang.RuntimeException: Field status_ for c.f.a.a.c not found. Known fields are [private static final c.f.a.a.c c.f.a.a.c.e, private static volatile c.b.b.a1 c.f.a.a.c.f]
       at com.google.protobuf.MessageSchema.a(MessageSchema.java:72)
       at com.google.protobuf.MessageSchema.a(MessageSchema.java:716)
       at com.google.protobuf.MessageSchema.a(MessageSchema.java:12)
       at com.google.protobuf.ManifestSchemaFactory.a(ManifestSchemaFactory.java:60)
       at com.google.protobuf.ManifestSchemaFactory.a(ManifestSchemaFactory.java:49)
       at com.google.protobuf.Protobuf.a(Protobuf.java:17)
       at com.google.protobuf.Protobuf.a(Protobuf.java:4)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:4)
       at com.google.protobuf.GeneratedMessageLite$Builder.k(GeneratedMessageLite.java:9)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java)
       at com.signify.hue.flutterreactiveble.channelhandlers.BleStatusHandler$listenToBleStatus$2.accept(BleStatusHandler.java:11)
       at com.signify.hue.flutterreactiveble.channelhandlers.BleStatusHandler$listenToBleStatus$2.accept(BleStatusHandler.java:2)
       at io.reactivex.internal.observers.LambdaObserver.a(LambdaObserver.java:8)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:47)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:8)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

--------------------------------

Caused by java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.StackTraceElement;@93b3227
       at io.flutter.plugin.common.StandardMessageCodec.a(StandardMessageCodec.java:392)
       at io.flutter.plugin.common.StandardMethodCodec.a(StandardMethodCodec.java:37)
       at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.a(EventChannel.java:45)
       at com.signify.hue.flutterreactiveble.channelhandlers.BleStatusHandler$listenToBleStatus$3.accept(BleStatusHandler.java:17)
       at com.signify.hue.flutterreactiveble.channelhandlers.BleStatusHandler$listenToBleStatus$3.accept(BleStatusHandler.java:2)
       at io.reactivex.internal.observers.LambdaObserver.a(LambdaObserver.java:13)
       at io.reactivex.internal.observers.LambdaObserver.a(LambdaObserver.java:25)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:47)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:8)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

------------------------------

Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:1720)
       at java.lang.Thread.getAllStackTraces(Thread.java:1796)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.a(CrashlyticsReportDataCapture.java:16)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.a(CrashlyticsReportDataCapture.java:4)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.a(CrashlyticsReportDataCapture.java:43)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.a(CrashlyticsReportDataCapture.java:42)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.a(SessionReportingCoordinator.java:19)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.a(SessionReportingCoordinator.java:32)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.call(CrashlyticsController.java:53)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.call(CrashlyticsController.java)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:2)
       at com.google.android.gms.tasks.zzf.run(zzf.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:919)

-------------------------------

FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
       at java.lang.Daemons$Daemon.run(Daemons.java:137)
       at java.lang.Thread.run(Thread.java:919)

----------------------------

pool-6-thread-1
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

--------------------------

pool-7-thread-3
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

--------------------------

FinalizerWatchdogDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:339)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:319)
       at java.lang.Daemons$Daemon.run(Daemons.java:137)
       at java.lang.Thread.run(Thread.java:919)

--------------------------

queued-work-looper
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------------

com.it_nomads.fluttersecurestorage.worker
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.os.HandlerThread.run(HandlerThread.java:67)

------------------------

OkHttp Http2Connection
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

-----------------------

Plugins used:

  flutter_secure_storage: ^3.3.3
  flutter_reactive_ble: ^2.7.3
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  carousel_slider: ^2.2.1
  percent_indicator: ^2.1.7+4
  fl_chart: ^0.12.0
  http: ^0.12.2
  async: ^2.4.2
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  sqflite: ^1.3.2+1
  shared_preferences: ^0.5.12+4
  path: ^1.7.0
  crypto: ^2.1.5
  url_launcher: ^5.7.10
  package_info: ^0.4.3+4

**Comment by remonh87** [comment]
Hmm that sounds like an proguard issue can you try to add `-keep class com.google.protobuf.** { *; }`  to your pro-guard-rules file? It is a bit probably linked to the fact firebase uses some outdated version from one or the other. I will do some triage in the coming days as well.

**Comment by remonh87** [comment]
@il-picchio  I did some triage on the exampel app and added the same depedencies to the pubspec.yaml as you did but for me the app runs normal. I would check your proguard rules and update gradle to version 6.5.1 this should hopefully fix the issue.

**Comment by il-picchio** [comment]
Hello, 
I am not using proguard in this project yet so I can't upgrade any rule unfortunatly

**Comment by remonh87** [comment]
I think proguard is on by default in release (if I am not mistaken) and this issue is related to that one. Also can you check your android tools version and gradle wrapper version ? For this library I recommend gradle-wrapper 6.5.1 and android tools version 4.1.2

**Comment by il-picchio** [comment]
Hello,

sorry for the delayed reply.
I confirm that the problem is not proguard (default is R8 though, proguard should be deprecated or whatever) which I am not using.
Finally I figured out what's going on. It was a problem in my gradle settings.

So thank you for your help, you have done a really good job with this plugin
