### ISSUE TITLE
writeCharacteristicWithoutResponse gives "not a valid Bluetooth address" error on Android

### ISSUE THREAD

**Issue by JimTompkins** [PhilipsHue/flutter_reactive_ble#325]
**Describe the bug**
I can scan for a custom device with a certain name, connect ok, get qualified characteristics, but when I make a call to writeCharacteristicWithoutResponse, I get an error "not a valid Bluetooth address".  See below for console log, my code and Flutter doctor output.

Thanks for any comments!

**To Reproduce**
1. scanForDevices
2. connectToDevice
3. get characteristic using QualifiedCharacteristic
4. writeCharacteristicWithoutResponse

**Expected behavior**
Write should cause an event on the custom peripheral.  

- [ ] This works in nRF Connect and the flutter_reactive_ble example program

**Smartphone / tablet**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0
 - Package version: ^3.1.1+1

**Peripheral device**
- Vendor, model: CUSTOM
- Does it run a custom firmware / software: yes,  firmware is based on Texas Instruments' simpleperipheral example with minor modification

**Additional context**
### Console log
I/flutter (26384): HF: start BLE scan
I/flutter (26384): REACTIVE_BLE: Start scanning for devices with arguments (withServices:[0000fff0-0000-1000-8000-00805f9b34fb], scanMode: ScanMode.lowLatency, locationServiceEnabled: true)
D/BluetoothAdapter(26384): STATE_ON
I/chatty  (26384): uid=10251(u0_a251) pool-4-thread-1 identical 4 lines
D/BluetoothAdapter(26384): STATE_ON
D/BluetoothLeScanner(26384): Start Scan with callback
D/BluetoothLeScanner(26384): onScannerRegistered() - status=0 scannerId=9 mScannerId=0
I/flutter (26384): REACTIVE_BLE: Received ScanResult(result: Result<DiscoveredDevice, GenericFailure<ScanFailure>?>.success(DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58)))
I/flutter (26384): HF: found HappyFeet, connecting to device...
I/flutter (26384): HF:    ID = DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58).id
I/flutter (26384): HF:    RSSI = DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58).rssi.toString()
I/flutter (26384): HF: stopping BLE scan
D/BluetoothAdapter(26384): STATE_ON
I/chatty  (26384): uid=10251(u0_a251) pool-4-thread-1 identical 2 lines
D/BluetoothAdapter(26384): STATE_ON
D/BluetoothLeScanner(26384): Stop Scan with callback
I/flutter (26384): HF: connectToDevice
[GETX] OPEN SNACKBAR
I/flutter (26384): REACTIVE_BLE: Start connecting to device with arguments (deviceId: A4:DA:32:D4:A2:40, servicesWithCharacteristicsToDiscover: null, timeout: 0:00:30.000000)
D/BluetoothGatt(26384): connect() - device: A4:DA:32:D4:A2:40, auto: false
D/BluetoothAdapter(26384): isSecureModeEnabled
D/BluetoothGatt(26384): registerApp()
I/flutter (26384): REACTIVE_BLE: Received ConnectionStateUpdate(deviceId: A4:DA:32:D4:A2:40, connectionState: DeviceConnectionState.connecting, failure: null)
D/BluetoothGatt(26384): registerApp() - UUID=b4653e4b-de33-4ad7-b8c8-f7eedbd48c1d
D/BluetoothGatt(26384): onClientRegistered() - status=0 clientIf=9
D/BluetoothGatt(26384): onClientConnectionState() - status=0 clientIf=9 device=A4:DA:32:D4:A2:40
I/flutter (26384): REACTIVE_BLE: Received ConnectionStateUpdate(deviceId: A4:DA:32:D4:A2:40, connectionState: DeviceConnectionState.connected, failure: null)
I/flutter (26384): HF: device connected
[GETX] OPEN SNACKBAR
I/flutter (26384): HF: getCharacteristics
I/flutter (26384): HF: added characteristics: QualifiedCharacteristic(characteristicId: 0000fff6-0000-1000-8000-00805f9b34fb, serviceId: 0000fff0-0000-1000-8000-00805f9b34fb, deviceId: DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58)).characteristicId
[GETX] REMOVING ROUTE null
[GETX] REMOVING ROUTE null
[GETX] CLOSE SNACKBAR
I/zygote64(26384): Do partial code cache collection, code=61KB, data=47KB
I/zygote64(26384): After code cache collection, code=61KB, data=47KB
I/zygote64(26384): Increasing code cache capacity to 256KB
D/BluetoothGatt(26384): onConnectionUpdated() - Device=A4:DA:32:D4:A2:40 interval=9 latency=0 timeout=1000 status=0
D/ViewRootImpl@6b8d02d[MainActivity](26384): ViewPostIme pointer 0
D/ViewRootImpl@6b8d02d[MainActivity](26384): ViewPostIme pointer 1
I/flutter (26384): HF: enabling beats
I/flutter (26384): REACTIVE_BLE: Write without response to QualifiedCharacteristic(characteristicId: 0000fff6-0000-1000-8000-00805f9b34fb, serviceId: 0000fff0-0000-1000-8000-00805f9b34fb, deviceId: DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58)), value: [1]
[GETX] OPEN SNACKBAR
E/MethodChannel#flutter_reactive_ble_method(26384): Failed to handle method call
E/MethodChannel#flutter_reactive_ble_method(26384): java.lang.IllegalArgumentException: DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58) is not a valid Bluetooth address
E/MethodChannel#flutter_reactive_ble_method(26384): 	at android.bluetooth.BluetoothDevice.<init>(BluetoothDevice.java:1117)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at android.bluetooth.BluetoothAdapter.getRemoteDevice(BluetoothAdapter.java:749)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.util.RxBleAdapterWrapper.getRemoteDevice(RxBleAdapterWrapper.java:36)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.DeviceModule.provideBluetoothDevice(DeviceModule.java:39)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.DeviceModule_ProvideBluetoothDeviceFactory.get(DeviceModule_ProvideBluetoothDeviceFactory.java:24)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.DeviceModule_ProvideBluetoothDeviceFactory.get(DeviceModule_ProvideBluetoothDeviceFactory.java:10)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.RxBleDeviceImpl_Factory.get(RxBleDeviceImpl_Factory.java:31)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.RxBleDeviceImpl_Factory.get(RxBleDeviceImpl_Factory.java:11)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at bleshadow.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.DaggerClientComponent$DeviceComponentImpl.provideDevice(DaggerClientComponent.java:509)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.internal.RxBleDeviceProvider.getBleDevice(RxBleDeviceProvider.java:43)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.polidea.rxandroidble2.RxBleClientImpl.getBleDevice(RxBleClientImpl.java:111)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.getConnection(ReactiveBleClient.kt:243)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.getConnection$default(ReactiveBleClient.kt:241)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.executeWriteOperation(ReactiveBleClient.kt:256)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.writeCharacteristicWithoutResponse(ReactiveBleClient.kt:194)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController$writeCharacteristicWithoutResponse$1.invoke(PluginController.kt:174)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController$writeCharacteristicWithoutResponse$1.invoke(PluginController.kt:24)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController.executeWriteAndPropagateResultToChannel(PluginController.kt:189)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController.writeCharacteristicWithoutResponse(PluginController.kt:174)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController.access$writeCharacteristicWithoutResponse(PluginController.kt:24)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController$pluginMethods$9.invoke(PluginController.kt:34)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController$pluginMethods$9.invoke(PluginController.kt:24)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.PluginController.execute$flutter_reactive_ble_debug(PluginController.kt:75)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.signify.hue.flutterreactiveble.ReactiveBlePlugin.onMethodCall(ReactiveBlePlugin.kt:39)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:862)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#flutter_reactive_ble_method(26384): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/flutter (26384): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58) is not a valid Bluetooth address, null, java.lang.IllegalArgumentException: DiscoveredDevice(id: A4:DA:32:D4:A2:40, name: HappyFeet, serviceData: {}, serviceUuids: [0000fff0-0000-1000-8000-00805f9b34fb], manufacturerData: [], rssi: -58) is not a valid Bluetooth address
E/flutter (26384): 	at android.bluetooth.BluetoothDevice.<init>(BluetoothDevice.java:1117)
E/flutter (26384): 	at android.bluetooth.BluetoothAdapter.getRemoteDevice(BluetoothAdapter.java:749)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.util.RxBleAdapterWrapper.getRemoteDevice(RxBleAdapterWrapper.java:36)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.DeviceModule.provideBluetoothDevice(DeviceModule.java:39)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.DeviceModule_ProvideBluetoothDeviceFactory.get(DeviceModule_ProvideBluetoothDeviceFactory.java:24)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.DeviceModule_ProvideBluetoothDeviceFactory.get(DeviceModule_ProvideBluetoothDeviceFactory.java:10)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.RxBleDeviceImpl_Factory.get(RxBleDeviceImpl_Factory.java:31)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.RxBleDeviceImpl_Factory.get(RxBleDeviceImpl_Factory.java:11)
E/flutter (26384): 	at bleshadow.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/flutter (26384): 	at com.polidea.rxandroidble2.DaggerClientComponent$DeviceComponentImpl.provideDevice(DaggerClientComponent.java:509)
E/flutter (26384): 	at com.polidea.rxandroidble2.internal.RxBleDeviceProvider.getBleDevice(RxBleDeviceProvider.java:43)
E/flutter (26384): 	at com.polidea.rxandroidble2.RxBleClientImpl.getBleDevice(RxBleClientImpl.java:111)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.getConnection(ReactiveBleClient.kt:243)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.getConnection$default(ReactiveBleClient.kt:241)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.executeWriteOperation(ReactiveBleClient.kt:256)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.ble.ReactiveBleClient.writeCharacteristicWithoutResponse(ReactiveBleClient.kt:194)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController$writeCharacteristicWithoutResponse$1.invoke(PluginController.kt:174)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController$writeCharacteristicWithoutResponse$1.invoke(PluginController.kt:24)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController.executeWriteAndPropagateResultToChannel(PluginController.kt:189)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController.writeCharacteristicWithoutResponse(PluginController.kt:174)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController.access$writeCharacteristicWithoutResponse(PluginController.kt:24)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController$pluginMethods$9.invoke(PluginController.kt:34)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController$pluginMethods$9.invoke(PluginController.kt:24)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.PluginController.execute$flutter_reactive_ble_debug(PluginController.kt:75)
E/flutter (26384): 	at com.signify.hue.flutterreactiveble.ReactiveBlePlugin.onMethodCall(ReactiveBlePlugin.kt:39)
E/flutter (26384): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (26384): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (26384): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:862)
E/flutter (26384): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26384): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (26384): 	at android.os.Looper.loop(Looper.java:142)
E/flutter (26384): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/flutter (26384): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26384): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/flutter (26384): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/flutter (26384): )
E/flutter (26384): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (26384): #1      MethodChannel._invokeMethod (package:flutter/src/service

### My code

class BluetoothBLEService {

  static const String DEVINFO_SERVICE_UUID =
      "0000180a-0000-1000-8000-00805f9b34fb";

  static const String MODEL_NUMBER_CHARACTERISTIC_UUID =
      "00002a24-0000-1000-8000-00805f9b34fb";
  static const String SERIAL_NUMBER_CHARACTERISTIC_UUID =
      "00002a25-0000-1000-8000-00805f9b34fb";
  static const String FIRMWARE_REV_CHARACTERISTIC_UUID =
      "00002a26-0000-1000-8000-00805f9b34fb";
  static const String HARDWARE_REV_CHARACTERISTIC_UUID =
      "00002a27-0000-1000-8000-00805f9b34fb";
  static const String SOFTWARE_REV_CHARACTERISTIC_UUID =
      "00002a28-0000-1000-8000-00805f9b34fb";
  static const String MANUFACTURER_NAME_CHARACTERISTIC_UUID =
      "00002a29-0000-1000-8000-00805f9b34fb";

  static const String HF_SERVICE_UUID =
      "0000fff0-0000-1000-8000-00805f9b34fb";
  // 6 characteristics:
  //    1 = read
  //    2 = read
  //    3 = write
  //    4 = notify      --> beat detection
  //    5 = read
  //    6 = write, read --> beat enable
  static const String CHAR1_CHARACTERISTIC_UUID =
      "0000fff1-0000-1000-8000-00805f9b34fb";
  static const String CHAR2_CHARACTERISTIC_UUID =
      "0000fff2-0000-1000-8000-00805f9b34fb";
  static const String CHAR3_CHARACTERISTIC_UUID =
      "0000fff3-0000-1000-8000-00805f9b34fb";
  static const String CHAR4_CHARACTERISTIC_UUID =
      "0000fff4-0000-1000-8000-00805f9b34fb";
  static const String CHAR5_CHARACTERISTIC_UUID =
      "0000fff5-0000-1000-8000-00805f9b34fb";
  static const String CHAR6_CHARACTERISTIC_UUID =
      "0000fff6-0000-1000-8000-00805f9b34fb";

  var _char1;
  var _char2;
  var _char3;
  var _char4;
  var _char5;
  var _char6;

  var _modelNumber;
  var _serialNumber;
  var _firmwareRev;
  var _hardwareRev;
  var _softwareRev;
  var _manufacturerName;

  final _connectionStateSubject =
  BehaviorSubject<BluetoothConnectionStateDTO>();
  Stream<BluetoothConnectionStateDTO> get connectionStateStream =>
      _connectionStateSubject.stream;

  bool isReady = false;
  bool isConnected = false;
  StreamSubscription? _subscription;
  StreamSubscription<ConnectionStateUpdate>? _connection;
  final _devices = <DiscoveredDevice>[];
  DiscoveredDevice? targetDevice;

  init() {
    isReady = false;
    isConnected = false;
    _ble.logLevel = LogLevel.verbose;  // change to none for release version
    _ble.statusStream.listen((status) {
      switch (_ble.status) {
        case BleStatus.unknown:
          print('HF: BLE status unknown');
          isReady = false;
          break;
        case BleStatus.unsupported:
          print('HF: BLE status unsupported');
          Get.snackbar('Bluetooth status', 'This device does not support Bluetooth', snackPosition: SnackPosition.BOTTOM);
          isReady = false;
          break;
        case BleStatus.unauthorized:
          print('HF: BLE status unauthorized');
          Get.snackbar('Bluetooth status', 'Authorize the HappyFeet app to use Bluetooth and location', snackPosition: SnackPosition.BOTTOM);
          isReady = false;
          break;
        case BleStatus.poweredOff:
          print('HF: BLE status powered off');
          Get.snackbar('Bluetooth status', 'Bluetooth is turned off.  Please turn it on', snackPosition: SnackPosition.BOTTOM);
          isReady = false;
          break;
        case BleStatus.locationServicesDisabled:
          print('HF: BLE status powered off');
          Get.snackbar('Bluetooth status', 'Enable location servies', snackPosition: SnackPosition.BOTTOM);
          isReady = false;
          break;
        case BleStatus.ready:
          print('HF: BLE status ready');
          isReady = true;
          break;
        default:
          print('HF: BLE status unknown');
          break;
      }
    });
  }

  // start the connection process by doing a scan of Bluetooth devices
  startConnection() {
    disconnectFromDevice();
    Uuid hfServiceUUID = Uuid.parse(HF_SERVICE_UUID);

    // check that the BLE status is ready before proceeding
    if (isReady != true) {
      // take action
      return;
    }

    print('HF: start BLE scan');
    _devices.clear();
    _subscription?.cancel();
    _subscription =
    _ble.scanForDevices(
        withServices: [hfServiceUUID],
        scanMode: ScanMode.lowLatency,
        requireLocationServicesEnabled: true).listen((device) {
        if (device.name == 'HappyFeet') {
           print('HF: found HappyFeet, connecting to device...');
           print('HF:    ID = $device.id');
           print('HF:    RSSI = $device.rssi.toString()');
           stopScan();
           targetDevice = device;
           Get.snackbar('Bluetooth status', 'Found Happy Feet!  Connecting...', snackPosition: SnackPosition.BOTTOM);
           connectToDevice();
           }
        },
        onError: (Object e) => print('HF: device scan fails with error: $e'),
        onDone: () => _onDoneScan(),
        );
  }

  _onDoneScan() {
    stopScan();
    if (targetDevice == null) {
 //     _connectionStateSubject.add(BluetoothConnectionStateDTO(
 //         bluetoothConnectionState: BluetoothConnectionState.FAILED));
    }
  }

  bool isBleConnected() {
    if (_connection == null) {
       return false;
    } else {
      return isConnected;
    }
  }

  connectToDevice() async {
    if (targetDevice == null) {
      print("HF: connectToDevice: targetDevice is null");
      return;
    } else {
      print("HF: connectToDevice");
    }

    try {
      _connection = _ble.connectToDevice(
        id: targetDevice!.id,
        connectionTimeout: const Duration(seconds:  30),
      ).listen((connectionState) async {
        if (connectionState.connectionState == DeviceConnectionState.connected) {
          isConnected = true;
          // for HappyFeet, set the MTU as small as possible
//          final mtu = await _ble.requestMtu(
//              deviceId: targetDevice!.id, mtu: 20);
//          print("HF: MTU size: $mtu");
//          await Future.delayed(Duration(milliseconds: 1000));
          print('HF: device connected');
          Get.snackbar('Bluetooth status', 'Connected!', snackPosition: SnackPosition.BOTTOM);
          getCharacteristics();
         } else {
          isConnected = false;
        }
      },
      onError: (Object e) => print('HF: connect to device fails with error: $e'),
      );
    } catch (err) {
      print('HF: device already connected');
    }
  }

  void getCharacteristics() {
    print('HF: getCharacteristics');
     _char1 = QualifiedCharacteristic(
        serviceId: Uuid.parse(HF_SERVICE_UUID),
        characteristicId: Uuid.parse(CHAR1_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    _char2 = QualifiedCharacteristic(
        serviceId: Uuid.parse(HF_SERVICE_UUID),
        characteristicId: Uuid.parse(CHAR2_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    _char3 = QualifiedCharacteristic(
        serviceId: Uuid.parse(HF_SERVICE_UUID),
        characteristicId: Uuid.parse(CHAR3_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    _char4 = QualifiedCharacteristic(
        serviceId: Uuid.parse(HF_SERVICE_UUID),
        characteristicId: Uuid.parse(CHAR4_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    _char5 = QualifiedCharacteristic(
        serviceId: Uuid.parse(HF_SERVICE_UUID),
        characteristicId: Uuid.parse(CHAR5_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    _char6 = QualifiedCharacteristic(
        serviceId: Uuid.parse(HF_SERVICE_UUID),
        characteristicId: Uuid.parse(CHAR6_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    _modelNumber = QualifiedCharacteristic(
        serviceId: Uuid.parse(DEVINFO_SERVICE_UUID),
        characteristicId: Uuid.parse(MODEL_NUMBER_CHARACTERISTIC_UUID),
        deviceId: targetDevice.toString());
    if (_char6 == null) {
      print('HF: error adding characteristic 6');
    } else {
      print('HF: added characteristics: $_char6.characteristicId');
    }
    return;
  }

  Future<void> stopScan() async {
    print('HF: stopping BLE scan');
    await _subscription?.cancel();
    _subscription = null;
  }

  // disconnect from HappyFeet
  Future<void> disconnectFromDevice() async {
    this.isConnected = false;
    _subscription?.cancel();
    try {
      print('HF: disconnecting from device');
      if (_connection != null) {
        await _connection?.cancel();
        Get.snackbar('Bluetooth status', 'Disconnecting', snackPosition: SnackPosition.BOTTOM);
      }
    } on Exception catch (e, _) {
      print('HF: Error disconnecting: $e');
    }
  }

  Future<void> disableBeat() async {
    if (_char6 == null) {
      print('HF: disableBeat: error: null characteristic');
      // error
    } else {
      print('HF: disabling beats');
      var response = await _ble.writeCharacteristicWithoutResponse(
          _char6, value: [0x00]);
    }
  }
  Future<void> enableBeat() async {
    if (_char6 == null) {
      print('HF: enableBeat: error: null characteristic');
      // error
    } else {
      print('HF: enabling beats');
      var response = await _ble.writeCharacteristicWithoutResponse(
          _char6, value: [0x01]);
    }
  }

  // read the accelerometer's whoAmI register reading from char2
  // the value should be 0x44
  Future<void> readWhoAmI() async {
    if (_char2 == null) return;
     try {
        List<int> value = await _ble.readCharacteristic(_char2!);
        if (value[0] == 0x44) {
          print("HF: correct whoAmI value was read");
        } else {
          print("HF: *** incorrect whoAmI value was read");
        }
      } catch (err) {
        print("HF: error readWhoAmI");
        print(err);
      }
  }

  // read the model number
  Future<String?> readModelNumber() async {
    String result = "ERROR";
    if (_modelNumber == null) return result;
      try {
        List<int> value = await _ble.readCharacteristic(_modelNumber!);
        // convert list of character codes to string
        result = String.fromCharCodes(value);
        if (result == null) {
          result = "ERROR: null result";
        }
        return result;
      } catch (err) {
        print("HF: error readModelNumber");
        print(err);
      }
  }

  // read char6 to see if beat sending is enabled or not
  Future readBeatEnable() async {
    if (_char6 == null) {
      print('HF: readBeatEnable: _char6 is null');
      return;
    } else {
      try {
        List<int> value = await _ble.readCharacteristic(_char6!);
        if (value[0] == 0x00) {
          print("HF: beats currently disabled.  Value = $value[0]");
          return(false);
        } else {
          print("HF: beats currently enabled.  Value = $value[0]");
          return(true);
        }
      } catch (err) {
        print("HF: error readBeatEnable");
        print(err);
      }
    }
  }

}

### Flutter doctor:
[√] Flutter (Channel master, 2.4.0-5.0.pre.147, on Microsoft Windows [Version 10.0.19043.1110], locale en-CA)
    • Flutter version 2.4.0-5.0.pre.147 at C:\src\flutter_windows_2.0.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 87eddcb1a0 (12 days ago), 2021-07-22 06:41:04 -0400
    • Engine revision d6c05fe884
    • Dart version 2.14.0 (build 2.14.0-341.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • SM G930W8 (mobile) • ce071717a385d10102 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 89.0.774.76

! Doctor found issues in 1 category.

**Comment by JimTompkins** [comment]
Fixed the problem by changing:

_char1 = QualifiedCharacteristic(
serviceId: Uuid.parse(HF_SERVICE_UUID),
characteristicId: Uuid.parse(CHAR1_CHARACTERISTIC_UUID),
deviceId: targetDevice.toString());


to

_char1 = QualifiedCharacteristic(
serviceId: Uuid.parse(HF_SERVICE_UUID),
characteristicId: Uuid.parse(CHAR1_CHARACTERISTIC_UUID),
deviceId: targetDevice!.id);

Rookie mistake!
