### ISSUE TITLE
[Crash] Android App Crash 

### ISSUE THREAD

**Issue by JAICHANGPARK** [PhilipsHue/flutter_reactive_ble#362]
**Describe the bug**

As soon as the application starts, it keeps crashing.
how to solve this problem? 

I checked this section 
https://github.com/PhilipsHue/flutter_reactive_ble#how-to-adjust-proguard-android

```
/vndksupport(28337): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
E/flutter (28337): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
E/flutter (28337): 	at android.os.Parcel.createException(Parcel.java:1966)
E/flutter (28337): 	at android.os.Parcel.readException(Parcel.java:1934)
E/flutter (28337): 	at android.os.Parcel.readException(Parcel.java:1884)
E/flutter (28337): 	at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:7318)
E/flutter (28337): 	at android.app.Activity.reportFullyDrawn(Activity.java:2092)
E/flutter (28337): 	at io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed(FlutterActivity.java:1100)
E/flutter (28337): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$1.onFlutterUiDisplayed(FlutterActivityAndFragmentDelegate.java:88)
E/flutter (28337): 	at io.flutter.embedding.android.FlutterView$2.onFlutterUiDisplayed(FlutterView.java:133)
E/flutter (28337): 	at io.flutter.embedding.engine.FlutterJNI.onFirstFrame(FlutterJNI.java:462)
E/flutter (28337): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (28337): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (28337): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (28337): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/flutter (28337): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28337): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter (28337): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter (28337): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (28337): 	at com.android.server.am.UserController.handleIncomingUser(UserController.java:1818)
E/flutter (28337): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25752)
E/flutter (28337): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25683)
E/flutter (28337): 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:26553)
E/flutter (28337): 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1264)
```

**Smartphone / tablet**
 - Device: Samsung Galaxy s8 
 - Package version: [4.0.0]

**Peripheral device**
- Vendor, model: [e.g. Fitbit Versa, iPhone SE, or CUSTOM]
- Does it run a custom firmware / software: yes / no

**Additional context**

## proguard 
```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.signify.hue.** { *; }
-keep class com.google.protobuf.** { *; }
-dontwarn io.flutter.embedding.**
```

## build.gradle

```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by remonh87** [comment]
@JAICHANGPARK It looks like the stacktrace is not related to us. We do not use NDK.  One thing: Did you add flutter-embedding V2 as metadata to the manifest?
