### ISSUE TITLE
WriteCharacteristicFailure.unknown, message: "Writechar timed-out"

### ISSUE THREAD

**Issue by avinashjoshi-canary** [PhilipsHue/flutter_reactive_ble#418]
This bug is produced by working with a nRF custom device.
The bug occurs some of times and once I terminate the app and restart it disappears. Not able figure out what is the matter.

I have tried both  `writeCharacteristicWithoutResponse` and `writeCharacteristicWithResponse`
following is the log

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: GenericFailure<WriteCharacteristicFailure>(code: WriteCharacteristicFailure.unknown, message: "Writechar timed-out")
E/flutter (22971): #0      Result.dematerialize.<anonymous closure> (package:reactive_ble_platform_interface/src/model/result.dart:22:13)
E/flutter (22971): #1      Result.iif (package:reactive_ble_platform_interface/src/model/result.dart:34:21)
E/flutter (22971): #2      Result.dematerialize (package:reactive_ble_platform_interface/src/model/result.dart:15:28)
E/flutter (22971): #3      ConnectedDeviceOperationImpl.writeCharacteristicWithoutResponse.<anonymous closure> (package:flutter_reactive_ble/src/connected_device_operation.dart:72:39)
E/flutter (22971): #4      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (22971): #5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (22971): <asynchronous suspension>

```

**Comment by akillika** [comment]
> I have this error when I Perform hot restart from android studio.

Same here. I have the device connected, but when I write the data, it pops this issue

**Comment by Baxi19** [comment]
I have the same error, any updated?

**Comment by Baxi19** [comment]
Could you please provide an update on this? I'm encountering the same error.

**Comment by TNorbury** [comment]
I'm encountering this error as well. Though my scenario seems different from those mentioned here:
* I'm using a Foreground Service to keep the app alive when the screen is turned off.
* I'm subscribed and getting a constant stream of data from my peripheral while the screen is off which is uploaded to the web (where I can verify that data is still be streamed and uploaded correctly).
* When I open the app back up and attempt to write to a characteristic I get this error and my app disconnects from the peripheral


Some other things to note:
* not scanning with a filter (which I know is required to establish a connection in a foreground service, however I do establish the connection before turning off the device), so I'm not sure if this is causing the connection to die out while the screen is off or something.
* I've tried disconnecting and reconnecting to my peripheral after resuming the app, but that doesn't seem to help.



Realize I'm getting into the weeds a bit by using the foreground service, but any insight would be appreciated!

**Comment by TNorbury** [comment]
Another interesting thing to note. It seems like this issue only happens with `writeWithResponse` and not `writeCharacteristicWithoutResponse`
