### ISSUE TITLE
Example App failes to start

### ISSUE THREAD

**Issue by ride4sun** [PhilipsHue/flutter_reactive_ble#476]
**Describe the bug**

When I run the example app I get this error:

Running "flutter pub get" in example...

```
Warning: You are using these overridden dependencies:
! flutter_reactive_ble 5.0.2 from path ..\packages\flutter_reactive_ble
! reactive_ble_mobile 5.0.2 from path ..\packages\reactive_ble_mobile
Launching lib\main.dart on motorola edge 2021 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter (10254): Observatory server failed to start after 1 tries
I/flutter (10254): Observatory server failed to start after 2 tries
I/flutter (10254): Observatory server failed to start after 3 tries
I/flutter (10254): Observatory server failed to start after 4 tries
I/flutter (10254): Observatory server failed to start after 5 tries
I/flutter (10254): Observatory server failed to start after 6 tries
I/flutter (10254): Observatory server failed to start after 7 tries
I/flutter (10254): Observatory server failed to start after 8 tries
I/flutter (10254): Observatory server failed to start after 9 tries
I/flutter (10254): Observatory server failed to start after 10 tries
I/flutter (10254): Observatory server failed to start after 11 tries
I/flutter (10254): Could not start Observatory HTTP server:
I/flutter (10254): SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 0
I/flutter (10254): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:988:7)
I/flutter (10254): <asynchronous suspension>
I/flutter (10254): #1      Server.startup.poll (dart:vmservice_io/vmservice_server.dart:425:19)
I/flutter (10254): <asynchronous suspension>
I/flutter (10254): #2      Server.startup (dart:vmservice_io/vmservice_server.dart:437:13)
I/flutter (10254): <asynchronous suspension>
I/flutter (10254): 
```

Platform and Flutter Version:
```
C:\Projects>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code, 32-bit edition (version 1.62.3)
[√] Connected device (3 available)

• No issues found!
```

**Comment by ride4sun** [comment]
After I added <uses-permission android:name="android.permission.INTERNET"/> its seems to be fine

**Comment by remonh87** [comment]
Flutter needs the internet permission in the manifest.  https://docs.flutter.dev/deployment/android#reviewing-the-app-manifest . We can add it to the debug manifest already.

**Comment by ride4sun** [comment]
> Flutter needs the internet permission in the manifest. https://docs.flutter.dev/deployment/android#reviewing-the-app-manifest . We can add it to the debug manifest already.

Not sure what that means, are you saying you going to fix that? Should the example not run out of the box without further do?

**Comment by Taym95** [comment]
> > Flutter needs the internet permission in the manifest. https://docs.flutter.dev/deployment/android#reviewing-the-app-manifest . We can add it to the debug manifest already.
> 
> 
> 
> Not sure what that means, are you saying you going to fix that? Should the example not run out of the box without further do? 

It is running out of box, I think this is just because of your machine setup, you can fix it if you want and the permission to manifest file, PR welcome!

**Comment by ride4sun** [comment]
Well, I opened the example folder as a project in Android Studio and I added the permission. Out of the box was not working form me.

**Comment by ram231** [comment]
I'm using Kotlin 1.6 in this screenshot. 
![image](https://user-images.githubusercontent.com/10434746/146938410-c9aa5015-7ffb-4776-a24c-5de7b0ff93c8.png)

Errors:

```sh

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':reactive_ble_mobile:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s
[!] Your project requires a newer version of the Kotlin Gradle plugin.
    Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then update D:\flutter_projects\bluetooth_app\android\build.gradle:
    ext.kotlin_version = '<latest-version>'
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```
Flutter suggested fix(But probably not recommend since I'm using flutter's generated build.gradle file which uses latest kotlin version):

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.bet_app_virgo"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

**Comment by MrCsabaToth** [comment]
What is this `Observatory server` BTW? I cannot even find it in the repository source code. If it's part of the Flutter runner or the SDK itself then we mustn't modify the example source because the cause is outside of it's jurisdiction.

**Comment by Taym95** [comment]
This log:

`I/flutter (10254): Observatory server failed to start after 1 tries`
 
Is coming from the flutter itself, that is why you can not find it in repository source code! 
From flutter code looks like `Observatory server` is a networking server that handles networking requests inside the flutter app (HTTP, WebSockets...)
