### ISSUE TITLE
non-reproducible fatal crash on Android

### ISSUE THREAD

**Issue by sh3rlock97** [PhilipsHue/flutter_reactive_ble#538]
**Describe the bug**
Pretty randomly after a lot of successful imports from a peripheral I get the following error on Android and the app crashes. It's working perfectly fine on iOS and even when throwing, the App shouldn't crash.

I think the error appears when due to slow deinitialize multiple BLE instances are running, but I don't know how to catch the error. I don't even know which part of the Code is generating the issue since it's inconsistent.

```
D[/BluetoothGatt]()( 8653): onClientConnectionState() - status=0 clientIf=20 device=28:FF:B2:50:88:0F
D[/BluetoothGatt]()( 8653): setCharacteristicNotification() - uuid: 00002a34-0000-1000-8000-00805f9b34fb enable: false
D[/BluetoothGatt]()( 8653): setCharacteristicNotification() - uuid: 00002a18-0000-1000-8000-00805f9b34fb enable: false
D[/BluetoothGatt]()( 8653): setCharacteristicNotification() - uuid: 00002a52-0000-1000-8000-00805f9b34fb enable: false
W[/System.err]()( 8653): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled[/disposed]() the flow or the exception has nowhere to go to begin with. Further reading: [https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling]() | com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
W[/System.err]()( 8653): 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:313)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.dispose(ObservableReplay.java:271)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableRefCount.timeout(ObservableRefCount.java:156)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableRefCount.cancel(ObservableRefCount.java:103)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.dispose(ObservableRefCount.java:252)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.mixed.CompletableAndThenObservable$AndThenObservableObserver.dispose(CompletableAndThenObservable.java:86)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
D[/BluetoothGatt]()( 8653): close()
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.dispose(SingleFlatMapObservable.java:84)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.dispose(SingleFlatMapObservable.java:84)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.dispose(ObservableFlatMap.java:588)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:510)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:504)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
W[/System.err]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
W[/System.err]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W[/System.err]()( 8653): 	at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:102)
W[/System.err]()( 8653): 	at com.signify.hue.flutterreactiveble.channelhandlers.CharNotificationHandler.unsubscribeFromAllNotifications(CharNotificationHandler.kt:59)
W[/System.err]()( 8653): 	at com.signify.hue.flutterreactiveble.channelhandlers.CharNotificationHandler.onCancel(CharNotificationHandler.kt:28)
W[/System.err]()( 8653): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:231)
W[/System.err]()( 8653): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:199)
W[/System.err]()( 8653): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
W[/System.err]()( 8653): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
W[/System.err]()( 8653): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W[/System.err]()( 8653): 	at android.os.Handler.handleCallback(Handler.java:938)
W[/System.err]()( 8653): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W[/System.err]()( 8653): 	at android.os.Looper.loop(Looper.java:246)
W[/System.err]()( 8653): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
W[/System.err]()( 8653): 	at java.lang.reflect.Method.invoke(Native Method)
W[/System.err]()( 8653): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
W[/System.err]()( 8653): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
W[/System.err]()( 8653): Caused by: com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
W[/System.err]()( 8653): 	at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:81)
D[/BluetoothGatt]()( 8653): unregisterApp() - mClientIf=20
W[/System.err]()( 8653): 	at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:298)
W[/System.err]()( 8653): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:882)
W[/System.err]()( 8653): 	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:42)
W[/System.err]()( 8653): 	at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:293)
W[/System.err]()( 8653): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:201)
W[/System.err]()( 8653): 	at android.os.Binder.execTransactInternal(Binder.java:1195)
W[/System.err]()( 8653): 	at android.os.Binder.execTransact(Binder.java:1159)
E[/AndroidRuntime]()( 8653): FATAL EXCEPTION: main
E[/AndroidRuntime]()( 8653): Process: ch.umana.umanacrossplatform, PID: 8653
E[/AndroidRuntime]()( 8653): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled[/disposed]() the flow or the exception has nowhere to go to begin with. Further reading: [https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling]() | com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:313)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.dispose(ObservableReplay.java:271)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableRefCount.timeout(ObservableRefCount.java:156)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableRefCount.cancel(ObservableRefCount.java:103)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.dispose(ObservableRefCount.java:252)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.operators.mixed.CompletableAndThenObservable$AndThenObservableObserver.dispose(CompletableAndThenObservable.java:86)
E[/AndroidRuntime]()( 8653): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
```

**Comment by sh3rlock97** [comment]
Should have read the FAQ 
https://github.com/PhilipsHue/flutter_reactive_ble#how-to-handle-the-ble-undeliverable-exception
